import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
const require = createRequire('C:/Users/dante.DESKTOP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const { chromium } = require('playwright');
const out = resolve(import.meta.dirname, '../../artifacts/catalog-interactions');
await mkdir(out, { recursive:true });
const browser = await chromium.launch({ channel:'msedge', headless:true });
const report = { url:'http://127.0.0.1:9480/', checks:[], profiles:[], costs:{} };
const check = (name, value) => { assert(value, name); report.checks.push(name); };
const delay = time => new Promise(resolve => setTimeout(resolve, time));
const percentile = (values, p) => [...values].sort((a,b)=>a-b)[Math.max(0,Math.ceil(values.length*p)-1)] || 0;
try {
  const context = await browser.newContext({ viewport:{width:1440,height:980}, deviceScaleFactor:1 });
  const page = await context.newPage();
  const errors = [], requests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => requests.push(request.url()));
  await page.goto(report.url, { waitUntil:'networkidle' });
  await page.evaluate(() => document.fonts.ready);
  check('Three equal real DEMO cards', await page.locator('.vehicle').count() === 3);
  const dimensions = await page.locator('.vehicle-link').evaluateAll(cards => cards.map(card => ({width:card.offsetWidth,height:card.offsetHeight})));
  check('Matching card dimensions', dimensions.every(card=>Math.abs(card.width-dimensions[0].width)<=1&&card.height===dimensions[0].height));
  const images = await page.locator('.vehicle-photo').evaluateAll(images => images.map(image => image.currentSrc));
  check('Same cover, one image per card', new Set(images).size===1&&await page.locator('.variant-c img').count()===1);
  check('No prices, cursor overlays or arrows', await page.locator('.vehicle-price,.card-cursor,.vehicle-arrow').count()===0);
  check('No production script or hero assets', !requests.some(url=>/hero|\.glb|\.hdr|three|gsap|wp-content/.test(url)));
  await page.screenshot({path:resolve(out,'comparison-desktop.png'),fullPage:true});
  const cdp = await context.newCDPSession(page);
  async function trace(variant) {
    const box = await page.locator('.variant-'+variant.toLowerCase()+' .vehicle-media').boundingBox();
    const traceEntries = [];
    const collect = ({value}) => traceEntries.push(...value);
    cdp.on('Tracing.dataCollected', collect);
    await cdp.send('Tracing.start', { categories:'devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame', transferMode:'ReportEvents' });
    await page.evaluate(() => {
      window.__CARD_LAB__.reset();
      window.__labFrames = []; let previous = performance.now();
      window.__labMeasure = true;
      const measure = time => { if(!window.__labMeasure)return;window.__labFrames.push(time-previous);previous=time;requestAnimationFrame(measure); };
      requestAnimationFrame(measure);
    });
    await page.mouse.move(box.x + 10, box.y + 10);
    for(let n=0;n<120;n++) {
      const phase = n/119;
      await page.mouse.move(box.x+20+(box.width-40)*phase,box.y+box.height*(.48+.16*Math.sin(phase*Math.PI*4)));
      await delay(12);
    }
    const samples = await page.evaluate(variant => {
      window.__labMeasure = false;
      return { frames:window.__labFrames.slice(1), js:window.__CARD_LAB__.metrics[variant] };
    }, variant);
    const completed = new Promise(resolve => cdp.once('Tracing.tracingComplete', resolve));
    await cdp.send('Tracing.end');
    await completed;
    cdp.off('Tracing.dataCollected',collect);
    const duration = name => traceEntries.filter(event=>event.name===name&&event.ph==='X').reduce((sum,event)=>sum+(event.dur||0),0)/1000;
    const count = name => traceEntries.filter(event=>event.name===name&&event.ph==='X').length;
    const cost = {rafSamples:samples.js.length,jsP95ms:percentile(samples.js,.95),frameP95ms:percentile(samples.frames,.95),observedFps:1000/(samples.frames.reduce((a,b)=>a+b,0)/samples.frames.length),paintEvents:count('Paint'),paintMs:duration('Paint'),layoutEvents:count('Layout'),layoutMs:duration('Layout'),rasterMs:duration('RasterTask'),traceMs:duration('PrePaint')};
    await writeFile(resolve(out,'trace-'+variant+'.json'),JSON.stringify({traceEvents:traceEntries.filter(event=>['Paint','Layout','RasterTask','PrePaint','Layerize','UpdateLayerTree','CompositeLayers'].includes(event.name))}));
    await page.screenshot({path:resolve(out,'hover-'+variant+'.png')});
    await page.mouse.move(2,2);
    await delay(650);
    check(variant+': no perpetual RAF at rest',await page.evaluate(()=>window.__CARD_LAB__.activeLoops===0));
    return cost;
  }
  for (const variant of ['A','B','C']) report.costs[variant] = await trace(variant);
  const cbox = await page.locator('.variant-c .vehicle-media').boundingBox();
  await page.mouse.move(cbox.x+cbox.width/2,cbox.y+cbox.height/2); await delay(300);
  await page.screenshot({path:resolve(out,'hover-C-center.png')});
  const a = page.locator('.variant-a .vehicle-link');
  const abox = await a.boundingBox();
  await page.mouse.move(abox.x+abox.width*.9, abox.y+70);
  await delay(250);
  check('A: counter-motion and fixed text',await a.evaluate(card=>parseFloat(card.querySelector('.vehicle-media').style.getPropertyValue('--photo-x'))<0&&getComputedStyle(card.querySelector('.vehicle-info')).transform==='none'));
  await page.mouse.down();
  check('Minimal press, normal cursor',await a.evaluate(card=>getComputedStyle(card).cursor==='pointer'&&getComputedStyle(card).transform!=='none'));
  await page.mouse.move(2,2); await page.mouse.up(); await delay(500);
  await page.locator('[data-view="B"]').click();
  check('Enlarged selector works',await page.locator('.concept:visible').count()===1&&(await page.locator('.variant-b .vehicle-link').boundingBox()).width>=600);
  await page.locator('.variant-b .vehicle-link').hover();
  await page.waitForTimeout(300);
  await page.screenshot({path:resolve(out,'enlarged-B.png'),fullPage:true});
  await page.locator('[data-view="all"]').click();
  await page.keyboard.press('Tab');
  await a.focus();
  check('Keyboard focus visible',await a.evaluate(card=>card===document.activeElement&&getComputedStyle(card).outlineStyle!=='none'));
  const popupReady = page.waitForEvent('popup');
  await a.click();
  const popup = await popupReady;
  await popup.waitForLoadState('domcontentloaded');
  check('Real DEMO detail opens immediately in another tab',popup.url().endsWith('/vehiculos/demo-vento/')&&await popup.locator('#unit-title').isVisible());
  await popup.close();
  check('No horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  check('No JavaScript errors',errors.length===0);
  report.profiles.push({name:'desktop',dimensions,requests:requests.length,errors});
  await context.close();
  const mobile = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  const touch = await mobile.newPage(); await touch.goto(report.url,{waitUntil:'networkidle'});
  check('Touch: clear desktop-only notice',await touch.locator('.touch-note').isVisible());
  check('Touch: static mask and no overflow',await touch.locator('.light-band').evaluate(element=>getComputedStyle(element).display==='none')&&await touch.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await touch.screenshot({path:resolve(out,'touch-static.png'),fullPage:true});
  await mobile.close();
  const reduced = await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});
  const staticPage = await reduced.newPage(); await staticPage.goto(report.url);
  await staticPage.locator('.variant-a .vehicle-link').hover(); await delay(200);
  check('Reduced motion: no pointer animation',await staticPage.evaluate(()=>window.__CARD_LAB__.metrics.A.length===0));
  await reduced.close();
} finally { await writeFile(resolve(out,'report.json'),JSON.stringify(report,null,2)); await browser.close(); }
console.log(JSON.stringify({passed:report.checks.length,costs:report.costs},null,2));
